# -*- mode: ruby -*-
# vi: set ft=ruby :
# editied Vagrantfile from: https://github.com/itu-devops/flask-minitwit-mongodb.git

Vagrant.configure("2") do |config|
  config.vm.box = 'digital_ocean'
  config.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.vm.synced_folder ".", "/vagrant", type: "rsync" #

  config.vm.define "MiniTwit-server", primary: true do |server| #create a VM named MiniTwit-server

    server.vm.provider :digital_ocean do |provider|
      provider.ssh_key_name = ENV["SSH_KEY_NAME"]
      provider.token = ENV["DIGITAL_OCEAN_TOKEN"]
      provider.image = 'ubuntu-22-04-x64'
      provider.region = 'fra1'
      provider.size = 's-1vcpu-1gb'
      provider.privatenetworking = true
    end

    server.vm.hostname = "MiniTwit-server"

    server.vm.provision "shell", inline: <<-SHELL
      # The following addresses an issue in DO's Ubuntu images, which still contain a lock file
      sudo fuser -vk -TERM /var/lib/apt/lists/lock
      sudo apt-get update

      sudo apt install docker-compose
      
      echo "================================================================="
      echo "=                   Starting docker container                   ="
      echo "================================================================="

      docker compose up -d --build #run in detached mode & rebuild images
      echo "DONE! Navigate your browser to:"  
      THIS_IP=`hostname -I | cut -d" " -f1`
      echo "http://${THIS_IP}:8080"
    SHELL
  end
end